const {Game,PITCHES,BATTERS,pitchPhysics,decideBatter}=require('../engine.js');
const assert=require('node:assert/strict');let passed=0;function test(name,fn){fn();passed++;console.log('PASS '+name);}
function event(g,kind){g.pending={type:'fast',grade:'PERFECT',speed:155,quality:75,x:.5,y:.5,inside:true,batterName:g.batter.name,pitchName:'포심',event:{kind,swing:kind!=='ball'&&kind!=='calledStrike'}};return g.finishPitch();}
test('Three strikes retire batter; second-strike fouls do not cause an out',()=>{const g=new Game();event(g,'calledStrike');event(g,'swingStrike');for(let i=0;i<5;i++)event(g,'foul');assert.equal(g.strikes,2);assert.equal(g.outs,0);const r=event(g,'swingStrike');assert.equal(r.call,'STRIKEOUT');assert.equal(g.outs,1);assert.equal(g.stats.ks,1);assert.equal(g.strikes,0);assert.equal(g.balls,0);assert.equal(g.batterIndex,1);});
test('Four balls force only occupied runners and score when bases loaded',()=>{const g=new Game();g.bases=[false,false,true];for(let i=0;i<4;i++)event(g,'ball');assert.deepEqual(g.bases,[true,false,true]);assert.equal(g.runs,0);g.bases=[true,true,true];for(let i=0;i<4;i++)event(g,'ball');assert.deepEqual(g.bases,[true,true,true]);assert.equal(g.runs,1);assert.equal(g.stats.walks,2);assert.equal(g.balls,0);});
test('Hits move bases and grand slam clears them',()=>{const g=new Game();event(g,'single');assert.deepEqual(g.bases,[true,false,false]);event(g,'double');assert.deepEqual(g.bases,[false,true,true]);event(g,'single');assert.equal(g.runs,1);assert.deepEqual(g.bases,[true,false,true]);event(g,'triple');assert.equal(g.runs,3);assert.deepEqual(g.bases,[false,false,true]);event(g,'homeRun');assert.equal(g.runs,5);assert.deepEqual(g.bases,[false,false,false]);g.bases=[true,true,true];event(g,'homeRun');assert.equal(g.runs,9);});
test('Three outs end inning; pitching and duplicate completion rejected',()=>{const g=new Game();for(let i=0;i<3;i++)event(g,'groundOut');assert.equal(g.finished,true);assert.equal(g.outs,3);assert.throws(()=>g.prepare(.5));assert.throws(()=>g.finishPitch());const points=g.points;g.resetInning();assert.equal(g.points,points);assert.equal(g.outs,0);assert.equal(g.finished,false);});
test('Perfect pitches near cap and all 9 target cells; fatigue reduces cap',()=>{for(const p of PITCHES){for(let cell=0;cell<9;cell++){const r=pitchPhysics(p,100,.5,cell,()=>.5);assert.equal(r.grade,'PERFECT');assert.ok(r.speed>=p.cap*.985-.1&&r.speed<=p.cap+.1);assert.equal(Math.floor(r.x*3),cell%3);assert.equal(Math.floor(r.y*3),Math.floor(cell/3));assert.ok(pitchPhysics(p,10,.5,cell,()=>.5).speed<r.speed);}}assert.equal(pitchPhysics(PITCHES[0],100,0,4,()=>.5).grade,'MISS');assert.equal(pitchPhysics(PITCHES[0],100,.56,4,()=>.5).grade,'GOOD');assert.equal(pitchPhysics(PITCHES[0],100,.5,4,()=>.5,true).grade,'MISS');});
test('Coaching transactional; pitching consumes stamina once; in-flight changes blocked',()=>{const g=new Game({points:160,stamina:100,unlocked:['fast']},()=>.99);g.learn('slider');assert.equal(g.points,0);assert.ok(g.unlocked.includes('slider'));assert.equal(g.pitchId,'slider');assert.throws(()=>g.learn('slider'));assert.throws(()=>g.learn('curve'));assert.equal(g.points,0);g.prepare(.5);assert.equal(g.stamina,92);assert.throws(()=>g.prepare(.5));assert.throws(()=>g.selectPitch('fast'));assert.throws(()=>g.rest());g.finishPitch();assert.equal(g.stamina,92);g.rest();assert.equal(g.stamina,100);});
test('AI watches outside balls and inside strikes; forced swing paths resolve fairly',()=>{const p={type:'fast',speed:155,quality:75,grade:'PERFECT',x:.5,y:.5,inside:true};assert.equal(decideBatter(p,BATTERS[0],{strikes:0},null,()=>.99).kind,'calledStrike');assert.equal(decideBatter({...p,x:2,inside:false},BATTERS[2],{strikes:0},null,()=>.99).kind,'ball');let seq=[0,.99];assert.equal(decideBatter(p,BATTERS[0],{strikes:0},null,()=>seq.shift()).kind,'swingStrike');seq=[0,0,0];assert.equal(decideBatter(p,BATTERS[0],{strikes:2},null,()=>seq.shift()).kind,'foul');});
test('Corrupted local progression sanitized; invalid targets and locked pitches rejected',()=>{const g=new Game({points:100,stamina:900,unlocked:['fast','fake','slider','slider']});assert.equal(g.stamina,100);assert.deepEqual(g.unlocked,['fast','slider']);assert.throws(()=>g.setTarget(9));assert.throws(()=>g.setTarget(.2));assert.throws(()=>g.selectPitch('curve'));assert.throws(()=>g.prepare(NaN));});
test('100 complete innings finish without illegal counts or bases',()=>{for(let i=0;i<100;i++){const g=new Game();let n=0;while(!g.finished&&n<250){if(g.stamina<g.pitch.drain)g.rest();g.setTarget(n%9);g.prepare(n%4===0?.07:.5);g.finishPitch();assert.ok(g.balls<=3&&g.strikes<=2&&g.outs<=3);assert.equal(g.bases.length,3);assert.ok(g.points>=0&&g.stamina>=0);n++;}assert.equal(g.finished,true);assert.ok(n<250);}});
console.log(passed+' meaningful checks passed');
