const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=require('node:path').resolve(__dirname,'..')+'/';const html=fs.readFileSync(root+'index.html','utf8'),engine=fs.readFileSync(root+'engine.js','utf8'),app=fs.readFileSync(root+'app.js','utf8');
const ids=new Set([...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]));for(const m of app.matchAll(/\$\('([^']+)'\)/g))assert.ok(ids.has(m[1]),'Missing UI element '+m[1]);
const elements={},handlers={},images=[],registered=[];let now=0,queue=[],draws=0;
const drawing=new Proxy({}, {get:(o,k)=>o[k]??(o[k]=()=>{draws++;}),set:(o,k,v)=>{o[k]=v;return true;}});
function element(id){return elements[id]??=( {id,style:{},classList:{toggle(){}},listeners:{},hidden:false,disabled:false,open:false,textContent:'',innerHTML:'',tagName:'DIV',addEventListener(t,f){this.listeners[t]=f;},setAttribute(){},showModal(){this.open=true;},close(){this.open=false;},getContext(){return drawing;},getBoundingClientRect(){return {left:0,top:0,width:1200,height:700};} });}
const math=Object.create(Math);math.random=()=>.99;
const context={console,Math:math,Image:class{constructor(){images.push(this);}},AbortController,performance:{now:()=>now},requestAnimationFrame:f=>{queue.push(f);return queue.length;},cancelAnimationFrame(){},localStorage:{getItem:()=>JSON.stringify({points:600,stamina:100,unlocked:['fast']}),setItem(){}},document:{hidden:false,activeElement:{tagName:'BODY'},getElementById:element,addEventListener:(type,fn)=>handlers[type]=fn,modelContext:{registerTool:t=>registered.push(t)}},window:{matchMedia:()=>({matches:false}),addEventListener(){}}};vm.createContext(context);vm.runInContext(engine,context);vm.runInContext(app,context);assert.equal(element('pitchBtn').disabled,true);images.forEach(img=>img.onload());assert.equal(element('pitchBtn').disabled,false);
const state=()=>registered[0].execute({});assert.equal(registered.length,2);
registered[1].execute({cell:0,pitch:'fast'});assert.equal(state().target,0);assert.throws(()=>registered[1].execute({cell:8,pitch:'curve'}));assert.equal(state().target,0);
function frame(t){now=t;const callbacks=queue;queue=[];callbacks.forEach(fn=>fn(now));}
function key(code,key=' '){let prevented=false;handlers.keydown({code,key,repeat:false,preventDefault(){prevented=true;}});return prevented;}
assert.equal(key('Space'),true);assert.equal(state().phase,'aim');assert.equal(element('targetGrid').innerHTML.includes('disabled'),true);frame(750);key('Space');assert.equal(state().phase,'flight');assert.equal(state().stamina,94);assert.throws(()=>registered[1].execute({cell:4,pitch:'fast'}));frame(2800);assert.equal(state().phase,'idle');assert.equal(state().strikes,1);assert.equal(state().stats.pitches,1);assert.equal(element('callTitle').textContent,'STRIKE');assert.ok(draws>50);
element('coachOpen').listeners.click();assert.equal(element('coachDialog').open,true);key('Space');assert.equal(state().phase,'idle');element('coachList').listeners.click({target:{closest:()=>({disabled:false,dataset:{learn:'slider'}})}});assert.ok(state().unlocked.includes('slider'));assert.equal(state().pitch,'슬라이더');element('coachClose').listeners.click();registered[1].execute({cell:0,pitch:'fast'});
for(let n=0;n<8;n++){const t=now;key('Space');frame(t+750);key('Space');frame(t+2800);}
assert.equal(state().outs,3);assert.equal(state().finished,true);assert.equal(state().stats.ks,3);assert.equal(element('endPanel').hidden,false);assert.equal(element('pitchBtn').disabled,true);const points=state().points;
element('nextInning').listeners.click();assert.equal(state().outs,0);assert.equal(state().finished,false);assert.equal(state().stamina,100);assert.equal(state().points,points);assert.equal(element('endPanel').hidden,true);
key('Space');context.document.hidden=true;handlers.visibilitychange();assert.equal(state().phase,'idle');assert.equal(state().stats.pitches,0);
console.log('PASS UI element links, image loading, canvas rendering calls, keyboard timing, animated pitch completion, dialog coaching, 3-out results, replay, tab pause, WebMCP valid/invalid state');
